import AppKit
import Carbon.HIToolbox
import os.log

private let insertLogger = Logger(subsystem: "com.swair.hearsay", category: "insert")

/// Inserts text at the current cursor position using Accessibility APIs
/// or clipboard + paste as fallback.
final class TextInserter {

    enum InsertionMethod {
        case accessibility  // Direct text insertion via AX API
        case clipboard      // Copy to clipboard + simulate Cmd+V
    }

    /// Insert text at the current cursor position, copying to clipboard permanently
    static func insert(_ text: String) {
        insertLogger.info("Inserting text; length=\(text.count)")
        copyToClipboard(text)
        simulatePaste()
    }

    /// Insert text at the cursor without keeping it on the clipboard.
    /// Temporarily uses the clipboard for the paste, then restores the previous contents.
    static func insertWithoutClipboard(_ text: String) {
        insertLogger.info("Inserting text without keeping clipboard; length=\(text.count)")
        let pasteboard = NSPasteboard.general

        // Save current clipboard contents across all types (text, images, files, etc.)
        let snapshot = PasteboardSnapshot.capture(from: pasteboard)
        let previousChangeCount = pasteboard.changeCount

        // Temporarily set our text marked with transient types so clipboard managers
        // (Maccy, Alfred, etc.) ignore this temporary hop and do not pollute history.
        pasteboard.clearContents()
        let tempItem = NSPasteboardItem()
        tempItem.setString(text, forType: .string)
        tempItem.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        tempItem.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        pasteboard.writeObjects([tempItem])

        // Paste, then restore
        simulatePaste {
            // Restore previous clipboard contents after paste completes
            // Only restore if nothing else has changed the clipboard in the meantime
            if pasteboard.changeCount == previousChangeCount + 1 {
                snapshot.restore(to: pasteboard)
                insertLogger.info("Clipboard restored")
            } else {
                insertLogger.info("Clipboard changed externally, skipping restore")
            }
        }
    }

    /// Just copy text to clipboard without pasting
    static func copyToClipboard(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        insertLogger.info("Copied to clipboard")
    }

    // MARK: - Clipboard + Paste

    private static func simulatePaste(completion: (() -> Void)? = nil) {
        // Delay to ensure clipboard is ready and focus is restored
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            insertLogger.info("Simulating Cmd+V...")

            // Create Cmd+V key event
            let source = CGEventSource(stateID: .combinedSessionState)

            // Key down
            if let keyDown = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true) {
                keyDown.flags = .maskCommand
                keyDown.post(tap: .cgAnnotatedSessionEventTap)
            }

            // Small delay between down and up
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.02) {
                let source = CGEventSource(stateID: .combinedSessionState)

                // Key up
                if let keyUp = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false) {
                    keyUp.flags = .maskCommand
                    keyUp.post(tap: .cgAnnotatedSessionEventTap)
                }

                insertLogger.info("Paste simulated")

                // Give a moment for the paste to be processed before restoring clipboard
                if let completion = completion {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                        completion()
                    }
                }
            }
        }
    }
}

// MARK: - Pasteboard Snapshot

extension TextInserter {
    /// Snapshots all items and representations from a pasteboard to allow full restoration.
    struct PasteboardSnapshot {
        struct Item {
            let dataByType: [(NSPasteboard.PasteboardType, Data)]
        }

        let items: [Item]

        static func capture(from pasteboard: NSPasteboard = .general) -> PasteboardSnapshot {
            guard let pbItems = pasteboard.pasteboardItems else {
                return PasteboardSnapshot(items: [])
            }

            let capturedItems = pbItems.map { pbItem -> Item in
                var dataByType: [(NSPasteboard.PasteboardType, Data)] = []
                for type in pbItem.types {
                    if let data = pbItem.data(forType: type) {
                        dataByType.append((type, data))
                    }
                }
                return Item(dataByType: dataByType)
            }

            return PasteboardSnapshot(items: capturedItems)
        }

        func restore(to pasteboard: NSPasteboard = .general) {
            pasteboard.clearContents()
            guard !items.isEmpty else { return }

            var newItems: [NSPasteboardItem] = []
            for item in items {
                let newItem = NSPasteboardItem()
                for (type, data) in item.dataByType {
                    newItem.setData(data, forType: type)
                }
                newItems.append(newItem)
            }
            pasteboard.writeObjects(newItems)
        }
    }
}
