import XCTest
@testable import Hearsay

final class TextInserterTests: XCTestCase {

    func testPasteboardSnapshotPreservesString() {
        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()
        pasteboard.setString("Hello World", forType: .string)

        let snapshot = TextInserter.PasteboardSnapshot.capture(from: pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("Temporary Replacement", forType: .string)
        XCTAssertEqual(pasteboard.string(forType: .string), "Temporary Replacement")

        snapshot.restore(to: pasteboard)
        XCTAssertEqual(pasteboard.string(forType: .string), "Hello World")
    }

    func testPasteboardSnapshotPreservesImageData() {
        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()

        // Create mock PNG data (or simple byte payload under png type)
        let sampleData = "mock-png-image-data".data(using: .utf8)!
        let item = NSPasteboardItem()
        item.setData(sampleData, forType: .png)
        pasteboard.writeObjects([item])

        // Verify image type is present and string is absent
        XCTAssertNil(pasteboard.string(forType: .string))
        XCTAssertEqual(pasteboard.data(forType: .png), sampleData)

        let snapshot = TextInserter.PasteboardSnapshot.capture(from: pasteboard)

        // Simulate Hearsay inserting temporary text
        pasteboard.clearContents()
        pasteboard.setString("transcribed text", forType: .string)
        XCTAssertEqual(pasteboard.string(forType: .string), "transcribed text")

        // Restore snapshot
        snapshot.restore(to: pasteboard)

        // Verify the original image data was completely restored
        XCTAssertNil(pasteboard.string(forType: .string))
        XCTAssertEqual(pasteboard.data(forType: .png), sampleData)
    }

    func testPasteboardSnapshotHandlesEmptyPasteboard() {
        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()

        let snapshot = TextInserter.PasteboardSnapshot.capture(from: pasteboard)
        XCTAssertTrue(snapshot.items.isEmpty)

        pasteboard.setString("New content", forType: .string)
        XCTAssertEqual(pasteboard.string(forType: .string), "New content")

        snapshot.restore(to: pasteboard)
        XCTAssertNil(pasteboard.string(forType: .string))
    }

    func testPasteboardChangeCountBehaviorWithWriteObjects() {
        let pasteboard = NSPasteboard.withUniqueName()
        let countBefore = pasteboard.changeCount

        pasteboard.clearContents()
        let countAfterClear = pasteboard.changeCount
        XCTAssertEqual(countAfterClear, countBefore + 1)

        let tempItem = NSPasteboardItem()
        tempItem.setString("sample", forType: .string)
        tempItem.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        tempItem.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        let wrote = pasteboard.writeObjects([tempItem])
        XCTAssertTrue(wrote)

        let countAfterWrite = pasteboard.changeCount
        // Notice whether writeObjects increments changeCount or keeps the clearContents count
        XCTAssertEqual(countAfterWrite, countAfterClear)
    }
}
